# Generated by Django 5.1.1 on 2024-11-17 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="imdb_id",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="release_date",
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("movie", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("movie", "user")},
        ),
    ]
