# Generated by Django 5.1.1 on 2024-11-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0003_movie_overview_movie_poster_path_mylist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="overview",
            field=models.TextField(),
        ),
    ]
