# Generated by Django 5.1.1 on 2024-11-27 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0006_alter_movie_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rating",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="user",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
