# Generated by Django 5.1.1 on 2024-11-29 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0008_delete_mylist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
